spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.1
  datasource:
    url: jdbc:postgresql://localhost:5432/pocketfinance
    username: pocket
    password: ${DB_PASSWORD:pocketpass}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Flyway irá rodar migrations em src/main/resources/db/migration
flyway:
  enabled: true
